appName: java-app
appReplicas: 1
registrySecret: my-registry-key
appContainerName: javamysqlapjavap
appImage: ariful95islam/java-app
appVersion: 1.0-SNAPSHOT
containerPort: 8080

servicePort: 8080

configName: db-config
configData:
  DB_SERVER: my-release-mysql-primary

secretName: db-secret
secretData: 
  DB_USER: my-user
  DB_PWD: my-pass
  DB_NAME: my-app-db
  MYSQL_ROOT_PASSWORD: secret-root-pass

regularData: {}
 # MY_ENV: my-value

ingress:
  hostName: my-java-app.com 
  pathType: Exact
  path: /


